# Обучение Нейронной сети - вход(2) скрытый(2) выход(1) (Логическое И)!

In [1]:
import numpy as np
import scipy.special

f_activation = lambda x: scipy.special.expit( x )

def f_derivative( x ):
  return x * ( 1 - x )

ls = 0.1

input_layer = np.array( [[0, 0, 1, 1],
                         [0, 1, 0, 1],
                         [1, 1, 1, 1]], dtype='float64' )

np.random.seed( 1358 )
synaptic_weight_1 = 2 * np.random.random( (2, 3) ) - 1
np.random.seed( 8531 )
synaptic_weight_2 = 2 * np.random.random( (1, 2) ) - 1

output_layer = np.array( [[0, 0, 0, 1]], dtype='float64' )

print( f'input_layer\n{ input_layer }')
print( f'synaptic_weight_1\n{ synaptic_weight_1 }')
print( f'synaptic_weight_2\n{ synaptic_weight_2 }')
print( f'output_layer\n{ output_layer }' )
print( f'--------------------------------------------------------------------' )

for i in range( 10000 ):
  
  H_input = np.dot( synaptic_weight_1, input_layer )
  H_output = f_activation( H_input )

  O_input = np.dot( synaptic_weight_2, H_output )
  O_output = f_activation( O_input )

  O_error = output_layer - O_output
  H_error = np.dot( synaptic_weight_2.T, O_error )

  synaptic_weight_2 += ls * np.dot( O_error * f_derivative( O_output ), np.transpose( H_output ) )
  synaptic_weight_1 += ls * np.dot( H_error * f_derivative( H_output ), np.transpose( input_layer ) )

print( f'O_output\n{O_output}' )
#print( f'H_input\n{ H_input }\nH_output\n{ H_output }' )
#print( f'O_input\n{ O_input }\nO_output\n{ O_output }' )
#print( f'--------------------------------------------------------------------' )
#print( f'O_error\n{ O_error }' )
#print( f'H_error\n{ H_error }' )
#print( f'--------------------------------------------------------------------' )
#print( f'update synaptic_weight_1\n{ synaptic_weight_1 }' )
#print( f'update synaptic_weight_2\n{ synaptic_weight_2 }' )

input_layer
[[0. 0. 1. 1.]
 [0. 1. 0. 1.]
 [1. 1. 1. 1.]]
synaptic_weight_1
[[ 0.86972016  0.36348073 -0.63030591]
 [ 0.84388098  0.84732604 -0.25890034]]
synaptic_weight_2
[[-0.26413596  0.99389447]]
output_layer
[[0. 0. 0. 1.]]
--------------------------------------------------------------------
O_output
[[0.01180395 0.01675211 0.01675259 0.99265087]]
