Обучение Нейронной Сети: 2 входа 1 выход (логическое ИЛИ)

In [1]:
import numpy as np
import scipy.special
f_activation = lambda x:scipy.special.expit(x)
def f_derivative(x):
    return x * (1 - x)
input_layer = np.array([[0, 0, 1],
                        [0, 1, 1],
                        [1, 0, 1],
                        [1, 1, 1]])
output_layer = np.array([[0],
                         [1],
                         [1],
                         [1]])
np.random.seed(1)
synaptic_weight = 2 * np.random.random((3, 1)) - 1

ls, al, DELTA_W_i = 0.7, 0.3, 0

for i in range(1000):

    O_input = np.dot(input_layer, synaptic_weight)
    O_output = f_activation(O_input)

    error = ((output_layer - O_output) ** 2) / len(output_layer)

    SIGMA_O = (output_layer - O_output) * ((1 - O_output) * O_output)

    GRAD_W = np.dot(input_layer.T, SIGMA_O)

    DELTA_W = ls * GRAD_W + al * DELTA_W_i

    synaptic_weight += DELTA_W

print(f'input_layer + bias\n{input_layer}')
print(f'output_layer\n{output_layer}')
print(f'synaptic_weight\n{synaptic_weight}')
print(f'O_input\n{O_input}\nO_output\n{O_output}\nerror\n{error}\nSIGMA_O\n{SIGMA_O}')
print(f'GRAD_W\n{GRAD_W}\nDELTA_W\n{DELTA_W}')
print(f'synaptic_weight\n{synaptic_weight}')


input_layer + bias
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
output_layer
[[0]
 [1]
 [1]
 [1]]
synaptic_weight
[[ 5.77905918]
 [ 5.77929344]
 [-2.63949302]]
O_input
[[-2.63890203]
 [ 3.13923489]
 [ 3.13900012]
 [ 8.91713704]]
O_output
[[0.06667633]
 [0.95848244]
 [0.9584731 ]
 [0.99986595]]
error
[[1.11143326e-03]
 [4.30926849e-04]
 [4.31120828e-04]
 [4.49258951e-09]]
SIGMA_O
[[-4.14930786e-03]
 [ 1.65214328e-03]
 [ 1.65287087e-03]
 [ 1.79679490e-08]]
GRAD_W
[[ 0.00165289]
 [ 0.00165216]
 [-0.00084428]]
DELTA_W
[[ 0.00115702]
 [ 0.00115651]
 [-0.00059099]]
synaptic_weight
[[ 5.77905918]
 [ 5.77929344]
 [-2.63949302]]
