<a href="https://colab.research.google.com/github/gukrasnov/Python_Neural_Network/blob/master/%D0%9E%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5_%D0%9D%D0%B5%D0%B9%D1%80%D0%BE%D0%BD%D0%BD%D0%BE%D0%B9_%D1%81%D0%B5%D1%82%D0%B8_2_%D0%B2%D1%85%D0%BE%D0%B4_1_%D0%B2%D1%8B%D1%85%D0%BE%D0%B4_(%D0%BB%D0%BE%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D0%98).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [133]:
import numpy as np
import scipy.special

f_activation = lambda x: scipy.special.expit( x )

def f_derivative( x ):
  return x * ( 1 - x )

ls = 0.1

input_layer = np.array( [[0, 0, 1, 1],
                         [0, 1, 0, 1],
                         [1, 1, 1, 1]], dtype='float64' )

np.random.seed(1358)
synaptic_weight = 2 * np.random.random( (1, 3) ) - 1

output_layer = np.array( [[0, 0, 0, 1]], dtype='float64' )

print( f'input_layer\n{ input_layer }\nsynaptic_weight\n{ synaptic_weight }\noutput_layer\n{ output_layer }' )
print( f'--------------------------------------------------------------------' )

for i in range( 100000 ):
  
  O_input = np.dot( synaptic_weight, input_layer )
  O_output = f_activation( O_input )

  O_error = output_layer - O_output
  
  synaptic_weight += ls * np.dot( O_error * f_derivative( O_output ), np.transpose( input_layer ) )

print( f'O_input\n{ O_input }\nO_output\n{ O_output }' )
print( f'--------------------------------------------------------------------' )
print( f'O_error\n{ O_error }' )
print( f'--------------------------------------------------------------------' )
print( f'update synaptic_weight\n{synaptic_weight}' )

input_layer
[[0. 0. 1. 1.]
 [0. 1. 0. 1.]
 [1. 1. 1. 1.]]
synaptic_weight
[[ 0.86972016  0.36348073 -0.63030591]]
output_layer
[[0. 0. 0. 1.]]
--------------------------------------------------------------------
O_input
[[-12.11562771  -4.09618609  -4.09618609   3.92325553]]
O_output
[[5.47327621e-06 1.63637750e-02 1.63637750e-02 9.80606923e-01]]
--------------------------------------------------------------------
O_error
[[-5.47327621e-06 -1.63637750e-02 -1.63637750e-02  1.93930772e-02]]
--------------------------------------------------------------------
update synaptic_weight
[[  8.01945216   8.01945216 -12.1156435 ]]
